// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcaqvcpfjdxllscsmlsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jYXF2Y3BmamR4bGxzY3NtbHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTAxODYsImV4cCI6MjA2MDM2NjE4Nn0.0J1CA_g81sJxLQmvEzTI-347y_APEaPau2SuRsGAOe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);