// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmwbccidogskuqsmqgtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtd2JjY2lkb2dza3Vxc21xZ3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzU1OTgsImV4cCI6MjA2MDUxMTU5OH0.Jva7H1xckU51K-ngnS3t7GJ-PscNu2wNf_8LFr2DzHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);